apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delavnice
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: delavnice
    newName: rg.fr-par.scw.cloud/djnd/delavnice
    newTag: '90262037262a0fb0961a2f01943f4f9cd25bfba1'
